# Workflow setup for building Native iOS project
workflows:
    name: iOS project # workflow name
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - flutter build ios --debug --no-codesign
    artifact:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app