# Workflow setup for building Native iOS project
workflows:
  ios-project: # workflow ID
    name: iOS project # workflow name
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - - flutter build ios --debug --no-codesign